version: "3.7"
services:
    app:
        build:
            args:
                user: ninacodemx
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ninacodemx
        container_name: ninacodemx-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/project.ini:/usr/local/etc/php/conf.d/project.ini
        networks:
            - ninacodemx
        depends_on:
            - db
    db:
        image: mariadb:10.7
        container_name: ninacodemx-db
        restart: unless-stopped
        ports:
            - ${DOCKER_DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/persistent:/var/lib/mysql
        networks:
            - ninacodemx
    nginx:
        image: nginx:stable-alpine
        container_name: ninacodemx-nginx
        restart: unless-stopped
        ports:
            - ${DOCKER_APP_PORT}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - ninacodemx
        depends_on:
            - db
networks:
    ninacodemx:
        driver: bridge
